/** WebP path for a JPEG/PNG public asset (generated by scripts/optimize-images.mjs). */
export function webpSrc(src: string): string {
	return src.replace(/\.(jpe?g|png)$/i, '.webp');
}

export function responsiveBase(src: string): string {
	return src.replace(/\.(jpe?g|png)$/i, '');
}

export function responsiveWebpSrcset(src: string, widths = [640, 960, 1280]): string {
	const base = responsiveBase(src);
	return widths.map((w) => `${base}-${w}w.webp ${w}w`).join(', ');
}

export function responsiveFallbackSrcset(src: string, widths = [640, 960, 1280]): string {
	const base = responsiveBase(src);
	const ext = src.match(/\.(jpe?g|png)$/i)?.[0] ?? '.jpg';
	return widths.map((w) => `${base}-${w}w${ext} ${w}w`).join(', ');
}
